server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: refresh
#logging:
#  level:
#    org:
#      hibernate : debug