server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    org:
#      hibernate : debug